/**
 * Extended skill inference patterns for metadata enhancement.
 * Only adds skillIds when description text clearly supports them.
 */

export interface MetadataSkillPattern {
  id: string;
  label: string;
  patterns: RegExp[];
}

export const METADATA_SKILL_PATTERNS: MetadataSkillPattern[] = [
  { id: "passing", label: "Passing", patterns: [/\bpass(?:es|ing)?\b/i, /\bpass the ball\b/i] },
  { id: "receiving", label: "Receiving", patterns: [/\breceiv(?:e|es|ing)\b/i, /\bshow myself for the ball\b/i, /\bready position\b/i] },
  { id: "throwing", label: "Throwing", patterns: [/\bthrow(?:s|ing)?\b/i] },
  { id: "catching", label: "Catching", patterns: [/\bcatch(?:es|ing)?\b/i] },
  { id: "kicking", label: "Kicking", patterns: [/\bkick(?:s|ing)?\b/i] },
  { id: "dribbling", label: "Dribbling", patterns: [/\bdribbl(?:e|es|ing)\b/i] },
  {
    id: "shooting",
    label: "Shooting",
    patterns: [/\bshoot(?:s|ing)?\b/i, /\bscor(?:e|es|ing)\b/i, /\bgoal\b/i],
  },
  { id: "finishing", label: "Finishing", patterns: [/\bfinish(?:es|ing)?\b/i] },
  { id: "defending", label: "Defending", patterns: [/\bdefend(?:s|ing)?\b/i, /\bdefensive\b/i, /\bprevent opponents\b/i, /\bdeny space\b/i] },
  { id: "attacking", label: "Attacking", patterns: [/\battack(?:s|ing)?\b/i, /\boffensive\b/i, /\bbuild an attack\b/i] },
  { id: "movement", label: "Movement", patterns: [/\bmovement\b/i, /\bmove(?:s|ing)?\b/i, /\blocomotor\b/i, /\bmove to and from base\b/i] },
  { id: "running", label: "Running", patterns: [/\brun(?:s|ning)?\b/i, /\bjog(?:ging)?\b/i] },
  { id: "sprinting", label: "Sprinting", patterns: [/\bsprint(?:s|ing)?\b/i] },
  { id: "jumping", label: "Jumping", patterns: [/\bjump(?:s|ing)?\b/i, /\bleap(?:s|ing)?\b/i, /\bhop(?:s|ping)?\b/i] },
  { id: "landing", label: "Landing", patterns: [/\bland(?:s|ing)?\b/i] },
  { id: "balance", label: "Balance", patterns: [/\bbalance(?:s|d|ing)?\b/i] },
  { id: "rolling", label: "Rolling", patterns: [/\broll(?:s|ing)?\b/i, /\bforward roll\b/i, /\bbackward roll\b/i] },
  { id: "travelling", label: "Travelling", patterns: [/\btravel(?:s|ling)?\b/i, /\btravell(?:e|ing)\b/i] },
  { id: "coordination", label: "Coordination", patterns: [/\bcoordination\b/i, /\bco-ordination\b/i] },
  { id: "agility", label: "Agility", patterns: [/\bagility\b/i, /\bchange of direction\b/i] },
  { id: "strength", label: "Strength", patterns: [/\bstrength\b/i, /\bbodyweight\b/i, /\bresistance\b/i] },
  { id: "endurance", label: "Endurance", patterns: [/\bendurance\b/i, /\bstamina\b/i, /\baerobic\b/i, /\bwithout stopping\b/i] },
  { id: "flexibility", label: "Flexibility", patterns: [/\bflexibility\b/i, /\bstretch(?:es|ing)?\b/i] },
  { id: "speed", label: "Speed", patterns: [/\bspeed\b/i, /\bvelocity\b/i, /\bquick(?:ly)?\b/i] },
  { id: "pacing", label: "Pacing", patterns: [/\bpace\b/i, /\bpacing\b/i, /\bconstant(?:ly)? fast\b/i, /\bmiddle distance\b/i] },
  { id: "technique", label: "Technique", patterns: [/\btechnique\b/i, /\btechnical\b/i, /\bproper technique\b/i] },
  { id: "serving", label: "Serving", patterns: [/\bserv(?:e|es|ing)\b/i, /\bunderarm serve\b/i, /\boverarm serve\b/i] },
  {
    id: "setting",
    label: "Setting",
    patterns: [/\bset(?:ting)? the ball\b/i, /\b3 sets \(volleyball\)/i, /\b3 sets\b/i, /\boverhead set\b/i],
  },
  { id: "digging", label: "Digging", patterns: [/\bdig(?:s|ging)?\b/i] },
  { id: "blocking", label: "Blocking", patterns: [/\bblock(?:s|ing)?\b/i] },
  { id: "spiking", label: "Spiking", patterns: [/\bspik(?:e|es|ing)\b/i, /\bsmash(?:es|ing)?\b/i] },
  { id: "positioning", label: "Positioning", patterns: [/\bposition(?:s|ing)?\b/i, /\bplaying positions?\b/i, /\bposition myself\b/i, /\bready position\b/i] },
  { id: "communication", label: "Communication", patterns: [/\bcommunicat(?:e|es|ing|ion)\b/i] },
  { id: "cooperation", label: "Cooperation", patterns: [/\bcooperat(?:e|es|ing|ion)\b/i, /\bparticipate cooperatively\b/i, /\bteam[\s-]?mates?\b/i, /\bteammates?\b/i] },
  { id: "teamwork", label: "Teamwork", patterns: [/\bteamwork\b/i, /\bteam work\b/i, /\bwork as a team\b/i, /\bteam member\b/i] },
  { id: "leadership", label: "Leadership", patterns: [/\blead(?:s|ing|ership)?\b/i, /\bleader\b/i] },
  { id: "responsibility", label: "Responsibility", patterns: [/\bresponsibilit(?:y|ies)\b/i, /\bresponsible\b/i] },
  { id: "fair-play", label: "Fair Play", patterns: [/\bfair play\b/i, /\bfairness\b/i] },
  { id: "inclusion", label: "Inclusion", patterns: [/\binclusi(?:on|ve)\b/i] },
  { id: "empathy", label: "Empathy", patterns: [/\bempathy\b/i, /\bempath(?:y|etic)\b/i] },
  { id: "respect", label: "Respect", patterns: [/\brespect(?:s|ing|ful)?\b/i] },
  { id: "officiating", label: "Officiating", patterns: [/\bofficiat(?:e|es|ing)\b/i, /\breferee\b/i, /\bumpire\b/i] },
  { id: "rules", label: "Rules", patterns: [/\brules?\b/i, /\bregulations?\b/i, /\byellow card\b/i, /\bfoul play\b/i] },
  { id: "decision-making", label: "Decision Making", patterns: [/\bdecision[\s-]?making\b/i, /\bmake decisions?\b/i, /\bchoose\b/i] },
  { id: "tactics", label: "Tactics", patterns: [/\btactics?\b/i, /\bstrateg(?:y|ies)\b/i] },
  { id: "analysis", label: "Analysis", patterns: [/\banalys(?:e|es|ing|is)\b/i, /\bevaluate\b/i, /\bobserve\b/i] },
  { id: "safety", label: "Safety", patterns: [/\bsafety\b/i, /\bsafe(?:ly)?\b/i, /\brisk\b/i, /\bhazard\b/i] },
  { id: "risk-management", label: "Risk Management", patterns: [/\brisk management\b/i, /\bmanage risk\b/i] },
  { id: "problem-solving", label: "Problem Solving", patterns: [/\bproblem[\s-]?solving\b/i, /\bsolve problems?\b/i] },
  { id: "orientation", label: "Orientation", patterns: [/\borientat(?:e|ion|ing)\b/i, /\bmap reading\b/i, /\bcompass\b/i] },
  { id: "coaching", label: "Coaching", patterns: [/\bcoach(?:es|ing)?\b/i] },
  { id: "organisation", label: "Organisation", patterns: [/\borganis(?:e|es|ing|ation)\b/i, /\borganiz(?:e|es|ing|ation)\b/i] },
  { id: "employability", label: "Employability", patterns: [/\bemployabilit(?:y|ies)\b/i, /\bworkplace\b/i, /\bemploy(?:ment|able)\b/i] },
  { id: "event-management", label: "Event Management", patterns: [/\bevent management\b/i, /\borganis(?:e|ing) (?:a |an )?event\b/i] },
  { id: "choreography", label: "Choreography", patterns: [/\bchoreograph(?:y|ies|ing)?\b/i, /\bsequence of movements?\b/i] },
  { id: "rhythm", label: "Rhythm", patterns: [/\brhythm\b/i, /\btempo\b/i, /\bbeat\b/i] },
  { id: "expression", label: "Expression", patterns: [/\bexpress(?:ion|ive)?\b/i, /\bcreativ(?:e|ity)\b/i] },
  { id: "performance", label: "Performance", patterns: [/\bperform(?:s|ing|ance)?\b/i] },
  { id: "body-control", label: "Body Control", patterns: [/\bbody control\b/i, /\bcontrol (?:my|their) body\b/i] },
  { id: "apparatus", label: "Apparatus", patterns: [/\bapparatus\b/i, /\bequipment\b/i, /\bfloor apparatus\b/i] },
  { id: "sequencing", label: "Sequencing", patterns: [/\bsequenc(?:e|es|ing)\b/i, /\bsequence of\b/i] },
  { id: "circuit-training", label: "Circuit Training", patterns: [/\bcircuit(?:s| training)?\b/i] },
  { id: "fitness-testing", label: "Fitness Testing", patterns: [/\bfitness test(?:s|ing)?\b/i, /\btesting fitness\b/i] },
];
