import type { LearningOutcome } from "./types";

export const LEARNING_OUTCOMES: LearningOutcome[] = [
  // ── Handball — Primary PE ─────────────────────────────────────────────
  {
    id: "pri-hb-pass-1",
    code: "PRI.HB.P1",
    description: "Demonstrate accurate chest and bounce passing in handball.",
    pathwayId: "primary-pe",
    topicIds: ["handball"],
    skillIds: ["passing"],
    valueIds: ["val-hb-teamwork"],
    assessmentIds: ["ass-hb-pass-1"],
    strand: "Invasion Games",
  },
  {
    id: "pri-hb-recv-1",
    code: "PRI.HB.R1",
    description: "Receive the ball with hands ready in handball.",
    pathwayId: "primary-pe",
    topicIds: ["handball"],
    skillIds: ["receiving", "passing"],
    valueIds: ["val-hb-teamwork"],
    assessmentIds: ["ass-hb-pass-2"],
    strand: "Invasion Games",
  },
  {
    id: "pri-hb-throw-1",
    code: "PRI.HB.T1",
    description: "Execute overarm throwing technique in handball.",
    pathwayId: "primary-pe",
    topicIds: ["handball"],
    skillIds: ["throwing"],
    valueIds: ["val-hb-fair-play"],
    assessmentIds: [],
    strand: "Invasion Games",
  },

  // ── Handball — Secondary PE ─────────────────────────────────────────────
  {
    id: "sec-hb-pass-1",
    code: "SEC.HB.P1",
    description: "Apply passing under defensive pressure in handball.",
    pathwayId: "secondary-pe",
    topicIds: ["handball"],
    skillIds: ["passing", "receiving"],
    valueIds: ["val-hb-fair-play", "val-hb-teamwork"],
    assessmentIds: ["ass-hb-pass-1", "ass-hb-pass-2"],
    strand: "Invasion Games",
  },
  {
    id: "sec-hb-shoot-1",
    code: "SEC.HB.S1",
    description: "Shoot accurately at goal from varied distances in handball.",
    pathwayId: "secondary-pe",
    topicIds: ["handball"],
    skillIds: ["shooting", "throwing"],
    valueIds: [],
    assessmentIds: [],
    strand: "Invasion Games",
  },

  // ── Handball — PE Option SEC ────────────────────────────────────────────
  {
    id: "opt-hb-pass-1",
    code: "OPT.HB.P1",
    description: "Analyse and apply advanced passing patterns in handball.",
    pathwayId: "pe-option-sec",
    topicIds: ["handball"],
    skillIds: ["passing", "receiving"],
    valueIds: ["val-hb-teamwork"],
    assessmentIds: ["ass-hb-pass-2"],
    strand: "Team Games",
  },

  // ── Football — Primary PE ───────────────────────────────────────────────
  {
    id: "pri-fb-pass-1",
    code: "PRI.FB.P1",
    description: "Pass accurately over short distances in football.",
    pathwayId: "primary-pe",
    topicIds: ["football"],
    skillIds: ["passing"],
    valueIds: [],
    assessmentIds: [],
    strand: "Invasion Games",
  },
  {
    id: "pri-fb-kick-1",
    code: "PRI.FB.K1",
    description: "Demonstrate controlled kicking with inside foot in football.",
    pathwayId: "primary-pe",
    topicIds: ["football"],
    skillIds: ["kicking"],
    valueIds: ["val-fb-fair-play"],
    assessmentIds: ["ass-fb-kick-1"],
    strand: "Invasion Games",
  },

  // ── Football — Secondary PE ─────────────────────────────────────────────
  {
    id: "sec-fb-kick-1",
    code: "SEC.FB.K1",
    description: "Kick for power and placement in football.",
    pathwayId: "secondary-pe",
    topicIds: ["football"],
    skillIds: ["kicking"],
    valueIds: ["val-fb-respect"],
    assessmentIds: ["ass-fb-kick-1"],
    strand: "Invasion Games",
  },
  {
    id: "sec-fb-finish-1",
    code: "SEC.FB.F1",
    description: "Finish effectively from crossing situations in football.",
    pathwayId: "secondary-pe",
    topicIds: ["football"],
    skillIds: ["finishing", "kicking"],
    valueIds: ["val-fb-respect"],
    assessmentIds: ["ass-fb-finish-1"],
    strand: "Invasion Games",
  },

  // ── Basketball — Middle School PE ───────────────────────────────────────
  {
    id: "mid-bb-pass-1",
    code: "MID.BB.P1",
    description: "Perform chest and bounce passes in basketball.",
    pathwayId: "middle-school-pe",
    topicIds: ["basketball"],
    skillIds: ["passing", "receiving"],
    valueIds: ["val-bb-inclusion"],
    assessmentIds: ["ass-bb-pass-1"],
    strand: "Invasion Games",
  },

  // ── Athletics — Primary PE ──────────────────────────────────────────────
  {
    id: "pri-ath-run-1",
    code: "PRI.AT.R1",
    description: "Demonstrate efficient running technique over sprint distances.",
    pathwayId: "primary-pe",
    topicIds: ["athletics"],
    skillIds: ["running"],
    valueIds: ["val-ath-responsibility"],
    assessmentIds: ["ass-ath-run-1"],
    strand: "Athletics",
  },

  // ── Fitness — Fitness Curriculum ────────────────────────────────────────
  {
    id: "fit-end-1",
    code: "FIT.E1",
    description: "Participate in continuous aerobic activities at moderate intensity.",
    pathwayId: "fitness-curriculum",
    topicIds: ["fitness"],
    skillIds: ["endurance"],
    valueIds: ["val-fit-responsibility"],
    assessmentIds: ["ass-fit-end-1"],
    strand: "Cardiovascular Fitness",
  },
  {
    id: "fit-str-1",
    code: "FIT.S1",
    description: "Perform bodyweight strength exercises with correct form.",
    pathwayId: "fitness-curriculum",
    topicIds: ["fitness"],
    skillIds: ["strength"],
    valueIds: ["val-fit-responsibility"],
    assessmentIds: [],
    strand: "Muscular Fitness",
  },

  // ── ALP PE — Handball ───────────────────────────────────────────────────
  {
    id: "alp-hb-pass-1",
    code: "ALP.HB.P1",
    description: "Lead peer passing drills in handball with clear instruction.",
    pathwayId: "alp-pe",
    topicIds: ["handball"],
    skillIds: ["passing", "receiving"],
    valueIds: ["val-hb-teamwork"],
    assessmentIds: ["ass-hb-pass-2"],
    strand: "Leadership in Sport",
  },

  // ── Exclusion samples (wrong topic for handball+passing) ────────────────
  {
    id: "sec-vb-serve-1",
    code: "SEC.VB.S1",
    description: "Demonstrate serving technique in volleyball.",
    pathwayId: "secondary-pe",
    topicIds: ["volleyball"],
    skillIds: ["serving", "technique"],
    valueIds: [],
    assessmentIds: [],
    strand: "Net Games",
  },
  {
    id: "pri-gym-bal-1",
    code: "PRI.GY.B1",
    description: "Perform balance sequences on floor apparatus.",
    pathwayId: "primary-pe",
    topicIds: ["gymnastics"],
    skillIds: ["balance"],
    valueIds: [],
    assessmentIds: [],
    strand: "Gymnastics",
  },
];
