import type { Skill } from "./types";

export const SKILLS: Skill[] = [
  // Invasion / net games
  { id: "passing", name: "Passing", topicIds: ["handball", "football", "basketball", "volleyball"] },
  { id: "receiving", name: "Receiving", topicIds: ["handball", "football", "basketball", "volleyball"] },
  { id: "throwing", name: "Throwing", topicIds: ["handball", "athletics", "outdoor-recreation"] },
  { id: "shooting", name: "Shooting", topicIds: ["handball", "basketball", "football"] },
  { id: "dribbling", name: "Dribbling", topicIds: ["football", "basketball"] },
  { id: "kicking", name: "Kicking", topicIds: ["football"] },
  { id: "finishing", name: "Finishing", topicIds: ["football"] },
  { id: "catching", name: "Catching", topicIds: ["basketball"] },
  { id: "defending", name: "Defending", topicIds: ["football", "basketball", "handball", "volleyball"] },
  { id: "attacking", name: "Attacking", topicIds: ["football", "basketball", "handball", "volleyball"] },
  { id: "serving", name: "Serving", topicIds: ["volleyball"] },
  { id: "setting", name: "Setting", topicIds: ["volleyball"] },
  { id: "digging", name: "Digging", topicIds: ["volleyball"] },
  { id: "blocking", name: "Blocking", topicIds: ["volleyball"] },
  { id: "spiking", name: "Spiking", topicIds: ["volleyball"] },
  { id: "positioning", name: "Positioning", topicIds: ["volleyball", "football", "basketball", "handball"] },
  { id: "movement", name: "Movement", topicIds: ["volleyball", "football", "basketball", "handball", "athletics", "gymnastics"] },

  // Athletics
  { id: "running", name: "Running", topicIds: ["athletics"] },
  { id: "sprinting", name: "Sprinting", topicIds: ["athletics"] },
  { id: "jumping", name: "Jumping", topicIds: ["athletics"] },
  { id: "pacing", name: "Pacing", topicIds: ["athletics"] },
  { id: "technique", name: "Technique", topicIds: ["athletics", "gymnastics", "volleyball"] },
  { id: "speed", name: "Speed", topicIds: ["athletics", "fitness"] },

  // Gymnastics / dance
  { id: "balance", name: "Balance", topicIds: ["gymnastics", "fitness"] },
  { id: "rolling", name: "Rolling", topicIds: ["gymnastics"] },
  { id: "travelling", name: "Travelling", topicIds: ["gymnastics"] },
  { id: "sequencing", name: "Sequencing", topicIds: ["gymnastics"] },
  { id: "body-control", name: "Body Control", topicIds: ["gymnastics"] },
  { id: "apparatus", name: "Apparatus", topicIds: ["gymnastics"] },
  { id: "choreography", name: "Choreography", topicIds: ["educational-dance"] },
  { id: "rhythm", name: "Rhythm", topicIds: ["educational-dance"] },
  { id: "expression", name: "Expression", topicIds: ["educational-dance"] },
  { id: "performance", name: "Performance", topicIds: ["educational-dance", "gymnastics"] },

  // Fitness
  { id: "endurance", name: "Endurance", topicIds: ["fitness"] },
  { id: "strength", name: "Strength", topicIds: ["fitness"] },
  { id: "flexibility", name: "Flexibility", topicIds: ["fitness"] },
  { id: "coordination", name: "Coordination", topicIds: ["fitness", "basketball"] },
  { id: "agility", name: "Agility", topicIds: ["fitness", "athletics"] },
  { id: "circuit-training", name: "Circuit Training", topicIds: ["fitness"] },
  { id: "fitness-testing", name: "Fitness Testing", topicIds: ["fitness"] },

  // Outdoor / values / vocational
  { id: "orientation", name: "Orientation", topicIds: ["outdoor-recreation"] },
  { id: "problem-solving", name: "Problem Solving", topicIds: ["outdoor-recreation"] },
  { id: "coaching", name: "Coaching", topicIds: ["alp-sports-vocational"] },
  { id: "organisation", name: "Organisation", topicIds: ["alp-sports-vocational"] },
  { id: "employability", name: "Employability", topicIds: ["alp-sports-vocational"] },
  { id: "event-management", name: "Event Management", topicIds: ["alp-sports-vocational"] },
  { id: "risk-management", name: "Risk Management", topicIds: ["alp-sports-vocational", "outdoor-recreation"] },
  { id: "officiating", name: "Officiating", topicIds: ["alp-sports-vocational", "football"] },
  { id: "rules", name: "Rules", topicIds: ["football", "basketball", "volleyball", "alp-sports-vocational"] },
  { id: "communication", name: "Communication", topicIds: ["sport-values", "teamwork", "leadership"] },
  { id: "cooperation", name: "Cooperation", topicIds: ["sport-values", "teamwork", "volleyball"] },
  { id: "teamwork", name: "Teamwork", topicIds: ["sport-values", "teamwork", "volleyball"] },
  { id: "leadership", name: "Leadership", topicIds: ["leadership", "sport-values", "alp-sports-vocational"] },
  { id: "responsibility", name: "Responsibility", topicIds: ["sport-values", "leadership"] },
  { id: "fair-play", name: "Fair Play", topicIds: ["sport-values"] },
  { id: "inclusion", name: "Inclusion", topicIds: ["sport-values"] },
  { id: "empathy", name: "Empathy", topicIds: ["sport-values"] },
  { id: "respect", name: "Respect", topicIds: ["sport-values"] },
  { id: "safety", name: "Safety", topicIds: ["outdoor-recreation", "alp-sports-vocational"] },
  { id: "tactics", name: "Tactics", topicIds: ["football", "basketball", "handball", "volleyball"] },
  { id: "decision-making", name: "Decision Making", topicIds: ["football", "basketball", "handball", "sport-values"] },
  { id: "analysis", name: "Analysis", topicIds: ["football", "basketball", "athletics"] },
];
