import type { LearningOutcome } from "../types";

export const LEARNING_OUTCOMES: LearningOutcome[] = [
  // General PE — Handball
  {
    id: "gpe-hb-pass-1",
    code: "GPE.HB.P1",
    description: "Demonstrate accurate chest and bounce passing in handball.",
    pathway: "general-pe",
    yearGroups: ["Year 7", "Year 8", "Year 9"],
    sport: "Handball",
    skills: ["Passing"],
    strand: "Invasion Games",
  },
  {
    id: "gpe-hb-pass-2",
    code: "GPE.HB.P2",
    description: "Apply passing under defensive pressure in small-sided handball.",
    pathway: "general-pe",
    yearGroups: ["Year 9", "Year 10", "Form 4"],
    sport: "Handball",
    skills: ["Passing", "Tactics"],
    strand: "Invasion Games",
  },
  {
    id: "gpe-hb-throw-1",
    code: "GPE.HB.T1",
    description: "Execute overarm and side-arm throwing techniques in handball.",
    pathway: "general-pe",
    yearGroups: ["Year 7", "Year 8"],
    sport: "Handball",
    skills: ["Throwing"],
    strand: "Invasion Games",
  },
  {
    id: "gpe-hb-throw-2",
    code: "GPE.HB.T2",
    description: "Throw accurately at goal from varied distances in handball.",
    pathway: "general-pe",
    yearGroups: ["Year 9", "Year 10", "Form 4", "Form 5"],
    sport: "Handball",
    skills: ["Throwing", "Shooting"],
    strand: "Invasion Games",
  },
  // General PE — Football
  {
    id: "gpe-fb-kick-1",
    code: "GPE.FB.K1",
    description: "Demonstrate controlled kicking with inside and laces in football.",
    pathway: "general-pe",
    yearGroups: ["Year 7", "Year 8", "Year 9"],
    sport: "Football",
    skills: ["Kicking"],
    strand: "Invasion Games",
  },
  {
    id: "gpe-fb-pass-1",
    code: "GPE.FB.P1",
    description: "Pass accurately over short and medium distances in football.",
    pathway: "general-pe",
    yearGroups: ["Year 7", "Year 8", "Year 9", "Year 10"],
    sport: "Football",
    skills: ["Passing", "Kicking"],
    strand: "Invasion Games",
  },
  {
    id: "gpe-fb-drib-1",
    code: "GPE.FB.D1",
    description: "Dribble with control while changing direction in football.",
    pathway: "general-pe",
    yearGroups: ["Year 8", "Year 9", "Year 10"],
    sport: "Football",
    skills: ["Dribbling"],
    strand: "Invasion Games",
  },
  // General PE — Basketball
  {
    id: "gpe-bb-pass-1",
    code: "GPE.BB.P1",
    description: "Perform chest, bounce, and overhead passes in basketball.",
    pathway: "general-pe",
    yearGroups: ["Year 7", "Year 8", "Year 9"],
    sport: "Basketball",
    skills: ["Passing", "Catching"],
    strand: "Invasion Games",
  },
  {
    id: "gpe-bb-shoot-1",
    code: "GPE.BB.S1",
    description: "Shoot using correct technique from close range in basketball.",
    pathway: "general-pe",
    yearGroups: ["Year 9", "Year 10", "Form 4"],
    sport: "Basketball",
    skills: ["Shooting"],
    strand: "Invasion Games",
  },
  // General PE — Athletics
  {
    id: "gpe-ath-mov-1",
    code: "GPE.AT.M1",
    description: "Demonstrate efficient running technique over sprint distances.",
    pathway: "general-pe",
    yearGroups: ["Year 7", "Year 8", "Year 9", "Year 10", "Form 4", "Form 5"],
    sport: "Athletics",
    skills: ["Movement"],
    strand: "Athletics",
  },
  {
    id: "gpe-ath-throw-1",
    code: "GPE.AT.T1",
    description: "Apply throwing technique in shot put and javelin activities.",
    pathway: "general-pe",
    yearGroups: ["Year 9", "Year 10", "Form 4"],
    sport: "Athletics",
    skills: ["Throwing"],
    strand: "Athletics",
  },
  // PE Option SEC
  {
    id: "sec-hb-pass-1",
    code: "SEC.HB.P1",
    description: "Analyse and apply advanced passing patterns in handball.",
    pathway: "pe-option-sec",
    yearGroups: ["Year 9", "Year 10", "Year 11"],
    sport: "Handball",
    skills: ["Passing", "Tactics"],
    strand: "Team Games",
  },
  {
    id: "sec-hb-throw-1",
    code: "SEC.HB.T1",
    description: "Evaluate throwing technique for power and accuracy in handball.",
    pathway: "pe-option-sec",
    yearGroups: ["Year 9", "Year 10", "Year 11"],
    sport: "Handball",
    skills: ["Throwing"],
    strand: "Team Games",
  },
  {
    id: "sec-fb-kick-1",
    code: "SEC.FB.K1",
    description: "Demonstrate advanced kicking for power and placement in football.",
    pathway: "pe-option-sec",
    yearGroups: ["Year 9", "Year 10", "Year 11"],
    sport: "Football",
    skills: ["Kicking"],
    strand: "Team Games",
  },
  {
    id: "sec-fit-end-1",
    code: "SEC.FT.E1",
    description: "Plan and monitor a personal endurance training programme.",
    pathway: "pe-option-sec",
    yearGroups: ["Year 10", "Year 11"],
    sport: "Fitness",
    skills: ["Endurance"],
    strand: "Health & Fitness",
  },
  // ALP PE
  {
    id: "alp-hb-pass-1",
    code: "ALP.HB.P1",
    description: "Lead peer passing drills in handball with clear instruction.",
    pathway: "alp-pe",
    yearGroups: ["Year 9", "Year 10", "Year 11", "Form 4", "Form 5"],
    sport: "Handball",
    skills: ["Passing", "Teamwork"],
    strand: "Leadership in Sport",
  },
  {
    id: "alp-bb-coord-1",
    code: "ALP.BB.C1",
    description: "Demonstrate coordination in multi-skill basketball sequences.",
    pathway: "alp-pe",
    yearGroups: ["Year 9", "Year 10", "Form 4"],
    sport: "Basketball",
    skills: ["Coordination", "Dribbling"],
    strand: "Skill Development",
  },
  // ALP Sports Vocational
  {
    id: "alp-sv-coach-1",
    code: "ALP.SV.C1",
    description: "Assist in coaching a junior team session with safe practice.",
    pathway: "alp-sports-vocational",
    yearGroups: ["Year 10", "Year 11", "Form 4", "Form 5"],
    sport: "General",
    skills: ["Teamwork", "Tactics"],
    strand: "Coaching",
  },
  {
    id: "alp-sv-fb-tac-1",
    code: "ALP.SV.F1",
    description: "Apply tactical formations in football match scenarios.",
    pathway: "alp-sports-vocational",
    yearGroups: ["Year 10", "Year 11", "Form 4"],
    sport: "Football",
    skills: ["Tactics", "Attacking", "Defending"],
    strand: "Match Play",
  },
  // Fitness Curriculum
  {
    id: "fit-str-1",
    code: "FIT.S1",
    description: "Perform bodyweight strength exercises with correct form.",
    pathway: "fitness-curriculum",
    yearGroups: ["Year 7", "Year 8", "Year 9", "Year 10", "Form 4", "Form 5"],
    sport: "Fitness",
    skills: ["Strength"],
    strand: "Muscular Fitness",
  },
  {
    id: "fit-flex-1",
    code: "FIT.F1",
    description: "Demonstrate flexibility routines for major muscle groups.",
    pathway: "fitness-curriculum",
    yearGroups: ["Year 7", "Year 8", "Year 9", "Year 10"],
    sport: "Fitness",
    skills: ["Flexibility"],
    strand: "Flexibility",
  },
  {
    id: "fit-end-1",
    code: "FIT.E1",
    description: "Participate in continuous aerobic activities at moderate intensity.",
    pathway: "fitness-curriculum",
    yearGroups: ["Year 8", "Year 9", "Year 10", "Form 4", "Form 5"],
    sport: "Fitness",
    skills: ["Endurance"],
    strand: "Cardiovascular Fitness",
  },
  // Sport Values
  {
    id: "sv-team-1",
    code: "SV.T1",
    description: "Demonstrate respect and fair play during competitive activities.",
    pathway: "sport-values",
    yearGroups: ["Year 7", "Year 8", "Year 9", "Year 10", "Form 4", "Form 5"],
    sport: "General",
    skills: ["Teamwork"],
    strand: "Fair Play",
  },
  {
    id: "sv-lead-1",
    code: "SV.L1",
    description: "Take responsibility for team conduct and sportsmanship.",
    pathway: "sport-values",
    yearGroups: ["Year 9", "Year 10", "Form 4", "Form 5"],
    sport: "General",
    skills: ["Teamwork", "Tactics"],
    strand: "Leadership",
  },
  {
    id: "sv-hb-fair-1",
    code: "SV.HB.F1",
    description: "Apply handball rules fairly and resolve disputes respectfully.",
    pathway: "sport-values",
    yearGroups: ["Year 8", "Year 9", "Year 10"],
    sport: "Handball",
    skills: ["Teamwork"],
    strand: "Fair Play",
  },
];

export function getLearningOutcomeById(id: string): LearningOutcome | undefined {
  return LEARNING_OUTCOMES.find((lo) => lo.id === id);
}
